//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPixzelle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videojuegos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string fechaLanzamiento { get; set; }
        public string Portada { get; set; }
        public string Compañia { get; set; }
        public string ConsolaJuego { get; set; }
    }
}
